export const US_STATE_BY_ABBREV: Record<string, string> = {
	// States
	AL: 'Alabama',
	AK: 'Alaska',
	AZ: 'Arizona',
	AR: 'Arkansas',
	CA: 'California',
	CO: 'Colorado',
	CT: 'Connecticut',
	DE: 'Delaware',
	DC: 'District of Columbia',
	FL: 'Florida',
	GA: 'Georgia',
	HI: 'Hawaii',
	ID: 'Idaho',
	IL: 'Illinois',
	IN: 'Indiana',
	IA: 'Iowa',
	KS: 'Kansas',
	KY: 'Kentucky',
	LA: 'Louisiana',
	ME: 'Maine',
	MD: 'Maryland',
	MA: 'Massachusetts',
	MI: 'Michigan',
	MN: 'Minnesota',
	MS: 'Mississippi',
	MO: 'Missouri',
	MT: 'Montana',
	NE: 'Nebraska',
	NV: 'Nevada',
	NH: 'New Hampshire',
	NJ: 'New Jersey',
	NM: 'New Mexico',
	NY: 'New York',
	NC: 'North Carolina',
	ND: 'North Dakota',
	OH: 'Ohio',
	OK: 'Oklahoma',
	OR: 'Oregon',
	PA: 'Pennsylvania',
	RI: 'Rhode Island',
	SC: 'South Carolina',
	SD: 'South Dakota',
	TN: 'Tennessee',
	TX: 'Texas',
	UT: 'Utah',
	VT: 'Vermont',
	VA: 'Virginia',
	WA: 'Washington',
	WV: 'West Virginia',
	WI: 'Wisconsin',
	WY: 'Wyoming',

	// Territories
	AS: 'American Samoa',
	GU: 'Guam',
	MP: 'Nothern Mariana Islands',
	PR: 'Puerto Rico',
	VI: 'Virgin Islands',
	UM: 'Minor Outlying Islands',
	FM: 'Federated States of Micronesia',
	MH: 'Marshall Islands',
	PW: 'Palau'
};

export const US_ABBREV_BY_STATE: Record<string, string> = {};
for (const [abbr, state] of Object.entries(US_STATE_BY_ABBREV)) {
	US_ABBREV_BY_STATE[state] = abbr;
}

export const CANADA_PROVINCE_ABBREVS: Record<string, string> = {
	AB: 'Alberta',
	BC: 'British Columbia',
	MB: 'Manitoba',
	NB: 'New Brunswick',
	NL: 'Newfoundland and Labrador',
	NT: 'Northwest Territories',
	NS: 'Nova Scotia',
	NU: 'Nunavut',
	ON: 'Ontario',
	PE: 'Prince Edward Island',
	QC: 'Quebec',
	SK: 'Saskatchewan',
	YT: 'Yukon'
};

export const statesHottestFirst = [
	'Hawaii',
	'Florida',
	'Louisiana',
	'Arizona',
	'Texas',
	'Mississippi',
	'Alabama',
	'Georgia',
	'South Carolina',
	'California',
	'Oklahoma',
	'Arkansas',
	'North Carolina',
	'Tennessee',
	'Nevada',
	'Kentucky',
	'Virginia',
	'District of Columbia',
	'Missouri',
	'Kansas',
	'Maryland',
	'Delaware',
	'West Virginia',
	'New Mexico',
	'New Jersey',
	'Indiana',
	'Illinois',
	'Oregon',
	'Ohio',
	'Washington',
	'Nebraska',
	'Pennsylvania',
	'Utah',
	'Rhode Island',
	'Connecticut',
	'New York',
	'Massachusetts',
	'Iowa',
	'Michigan',
	'Idaho',
	'Colorado',
	'South Dakota',
	'Wisconsin',
	'New Hampshire',
	'Montana',
	'Vermont',
	'Wyoming',
	'Maine',
	'Minnesota',
	'North Dakota',
	'Alaska'
];

export const stateAbbrsCoolestFirst: string[] = [];
for (const state of statesHottestFirst) {
	stateAbbrsCoolestFirst.push(US_ABBREV_BY_STATE[state]);
}
stateAbbrsCoolestFirst.reverse();
